{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8425000d-efca-4b1c-8577-e60d1cb09b87",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression  # Corrected the typo here\n",
    "import matplotlib.pyplot as plt  # Corrected the import statement here\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "318fe093-c281-4940-b947-e327d9805d72",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0, 1],\n",
       "       [2, 3],\n",
       "       [4, 5],\n",
       "       [6, 7],\n",
       "       [8, 9]])"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# lets create data and arrange\n",
    "X= np.arange(10).reshape((5,2))\n",
    "X\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6d615ef7-be43-44c2-b85d-40fdfb18fada",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "range(0, 5)"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y= range(5)\n",
    "y\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "002e3c35-4d9d-4d79-961f-d5475222d9dd",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "7dca6061-b415-4ab6-8de3-a0dc8e416ad6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0, 1],\n",
       "       [6, 7],\n",
       "       [8, 9]])"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "7081cb8a-54ad-4fb2-9692-bd7a30476e8f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-2 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: black;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-2 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-2 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-2 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-2 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-2 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: block;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-2 div.sk-toggleable__content {\n",
       "  max-height: 0;\n",
       "  max-width: 0;\n",
       "  overflow: hidden;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  max-height: 200px;\n",
       "  max-width: 100%;\n",
       "  overflow: auto;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-2 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-2 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-2 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-2 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-2 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-2 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 1ex;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-2 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-2 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-2 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "</style><div id=\"sk-container-id-2\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator  sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-2\" type=\"checkbox\" checked><label for=\"sk-estimator-id-2\" class=\"sk-toggleable__label  sk-toggleable__label-arrow \">&nbsp;&nbsp;LinearRegression<a class=\"sk-estimator-doc-link \" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LinearRegression.html\">?<span>Documentation for LinearRegression</span></a><span class=\"sk-estimator-doc-link \">i<span>Not fitted</span></span></label><div class=\"sk-toggleable__content \"><pre>LinearRegression()</pre></div> </div></div></div></div>"
      ],
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model=LinearRegression()\n",
    "model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "eca9acf9-0098-4890-9676-4d46d5a8f191",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-3 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: black;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-3 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-3 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-3 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-3 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-3 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: block;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-3 div.sk-toggleable__content {\n",
       "  max-height: 0;\n",
       "  max-width: 0;\n",
       "  overflow: hidden;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  max-height: 200px;\n",
       "  max-width: 100%;\n",
       "  overflow: auto;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-3 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-3 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-3 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-3 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-3 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-3 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-3 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-3 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-3 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 1ex;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-3 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-3 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-3 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "</style><div id=\"sk-container-id-3\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-3\" type=\"checkbox\" checked><label for=\"sk-estimator-id-3\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow fitted\">&nbsp;&nbsp;LinearRegression<a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LinearRegression.html\">?<span>Documentation for LinearRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></label><div class=\"sk-toggleable__content fitted\"><pre>LinearRegression()</pre></div> </div></div></div></div>"
      ],
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "#fit() is a function to train \n",
    "model.fit(X_train,y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "253eeaf3-d93a-4553-b538-115d2078803e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([2., 1.])"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# predict() is to predict \n",
    "prediction=model.predict(X_test)\n",
    "prediction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "cd2c764e-a581-4887-8474-a22aae187772",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.colorbar.Colorbar at 0x1c26ec46c30>"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAmwAAAH/CAYAAADqj4FVAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAAA6t0lEQVR4nO3de3RV9Z3//9dJICcIORGQ3CBcFAS53xQTWkFFaaQMqbOQMjhEQH/TNlQwbafGtoJVDNaFxVYawAtYMY2XCnYYhUYsMAxBQiD9Ao4oiiRqEmqLOSTCAc7evz+U1EgSssM+OXvnPB9rfdbq2dn7s99nsWzeeX9uHtM0TQEAAMCxosIdAAAAAJpHwgYAAOBwJGwAAAAOR8IGAADgcCRsAAAADkfCBgAA4HAkbAAAAA5HwgYAAOBwJGwAAAAOR8IGAADgcCRsAAAArbB06VJ5PB4tXLiw2fteeuklDRo0SLGxsRo2bJhee+01y+8iYQMAALCopKREq1at0vDhw5u9b+fOnZo5c6bmzZunffv2KTMzU5mZmTpw4ICl93k4/B0AAKDlamtrNXr0aP3ud7/TQw89pJEjR2r58uWN3jtjxgzV1dVp48aN9deuvfZajRw5UitXrmzxOztcbNBWGYahTz75RHFxcfJ4PG39egAA0AqmaerEiRNKSUlRVFTbD9CdOnVKp0+fDknfpmmel5N4vV55vd5G78/OztaUKVM0adIkPfTQQ832XVxcrJycnAbXJk+erA0bNliKsc0Ttk8++USpqalt/VoAAGCDiooK9erVq03feerUKfXr00VVx4Ih6b9Lly6qra1tcG3RokVavHjxefcWFhZq7969KikpaVHfVVVVSkxMbHAtMTFRVVVVlmJs84QtLi5O0hf/4D6fr61fDwAAWsHv9ys1NbX+93hbOn36tKqOBXW0tK98cfZW9/wnDPUZ8+F5eUlj1bWKigotWLBARUVFio2NtTWOC2nzhO1cydHn85GwAQDgMuGcztQlzqMucfa+31DL85LS0lIdO3ZMo0ePrr8WDAa1fft2PfHEEwoEAoqOjm7wTFJSkqqrqxtcq66uVlJSkqU4WSUKAADQAjfeeKP279+vsrKy+jZ27FjNmjVLZWVl5yVrkpSWlqYtW7Y0uFZUVKS0tDRL727zChsAAEBrBE1DQZv3tgiaRovvjYuL09ChQxtc69y5s7p3715/ffbs2erZs6fy8vIkSQsWLNCECRO0bNkyTZkyRYWFhdqzZ49Wr15tKU4qbAAAADYpLy9XZWVl/ef09HQVFBRo9erVGjFihF5++WVt2LDhvMTvQtp8Hza/36/4+HjV1NQwhw0AAJcI5+/vc++uOtQ7JIsOkgaWOz4vYUgUAAC4giFDLR/AbHmfbsCQKAAAgMNRYQMAAK4QNE0FbZ7JZXd/oUKFDQAAwOGosAEAAFcwZMqQvRUxu/sLFSpsAAAADkeFDQAAuIIhU0EqbAAAAHAiKmwAAMAVInkOGwkbAAAuZ5qGdPp/ZAaKJRnyxIyWvDfK4+kY7tBgE8tDoidOnNDChQvVp08fderUSenp6SopKQlFbAAA4ALMs0dlfvotmcfvkj7/vfT5Opmf3S3zb9fLPHMg3OHZ6tw+bHY3N7CcsN15550qKirSc889p/379+vmm2/WpEmT9PHHH4ciPgAA0ATTqJX5j9ulYMWXV85+2SQZn8r8R5bMYFW4wrOdEaLmBpYStpMnT+qPf/yjfvWrX+m6665T//79tXjxYvXv31/5+fmhihEAADTm5AbJOCYp2MgPDcmsk/l5QRsHhVCwNIft7NmzCgaDio2NbXC9U6dO2rFjR6PPBAIBBQKB+s9+v78VYQIAgK8zT712gTsM6dRGKS6nTeIJtWAItvWwu79QsVRhi4uLU1pamh588EF98sknCgaDWrdunYqLi1VZWdnoM3l5eYqPj69vqamptgQOAEDEM2ulCyUcxudtEgpCy/Ictueee06maapnz57yer36zW9+o5kzZyoqqvGucnNzVVNTU98qKioavQ8AAFjU4UpJ0c3cECV16N9W0YRc0AxNcwPLCdsVV1yhbdu2qba2VhUVFdq9e7fOnDmjyy+/vNH7vV6vfD5fgwYAAC6e55KZanz+2jmGPJ1ntVU4CKFWn3TQuXNnJScn6/jx49q8ebOmTZtmZ1wAAOACPDFjpE7/fu7T138qeb8leSe3dVghE8mrRC1vnLt582aZpqmBAwfq8OHD+slPfqJBgwZpzpw5oYgPAAA0w+P7udTxSpl1T0nBo19cjEqUp/Md0iVZ8ng4hbI9sJyw1dTUKDc3Vx999JG6deumf/3Xf9WSJUvUsSO7KQMA0NY8Ho90yQyp021fbvFhSlEJ7TJRM+RR8LxK4sX36QaWE7bbbrtNt912WyhiAQAAreTxeKToxHCHEVKG+UWzu083aH/pNwAAQDvD4e8AAMAVgiEYErW7v1ChwgYAAOBwVNgAAIArUGEDAACAY1FhAwAArmCYHhmmzdt62NxfqFBhAwAAcDgqbAAAwBUieQ4bCRsAAHCFoKIUtHlwMGhrb6HDkCgAAIDDUWEDAACuYIZg0YHJogMAAADYgQobAABwhUhedECFDQAAwOGosAEAAFcImlEKmjavEjVt7S5kqLABAAA4HBU2AADgCoY8MmyuNRlyR4mNhA0AALgCiw4AAADgWFTYAACAK4Rm0YE7hkSpsAEAADgcFTYAAOAKXyw6sHfOmd39hQoVNgAAAIejwgYAAFzBUJSCEbqtBxU2AAAAh6PCBgAAXIFVogAAAA5nKCokraXy8/M1fPhw+Xw++Xw+paWl6fXXX2/y/rVr18rj8TRosbGxrfruVNgAAABaoFevXlq6dKkGDBgg0zT17LPPatq0adq3b5+GDBnS6DM+n0+HDh2q/+zxtG5VKgkbAABwhaDpUdC0+WgqC/1NnTq1weclS5YoPz9fu3btajJh83g8SkpKuqgYJYZEAQAA5Pf7G7RAINDs/cFgUIWFhaqrq1NaWlqT99XW1qpPnz5KTU3VtGnTdPDgwVbFR8IGAABcIfjlth52N0lKTU1VfHx8fcvLy2s0hv3796tLly7yer363ve+p/Xr12vw4MGN3jtw4EA988wzevXVV7Vu3ToZhqH09HR99NFHlr87Q6IAACDiVVRUyOfz1X/2er2N3jdw4ECVlZWppqZGL7/8srKysrRt27ZGk7a0tLQG1bf09HRdddVVWrVqlR588EFL8ZGwAQAAVzDMKBk2b+thfLmtx7mVnxcSExOj/v37S5LGjBmjkpISPf7441q1atUFn+3YsaNGjRqlw4cPW46TIVEAAIBWMgzjgvPdzgkGg9q/f7+Sk5Mtv4cKGwAAcIWvzjmzr8+Wb5ybm5urjIwM9e7dWydOnFBBQYG2bt2qzZs3S5Jmz56tnj171s9/++Uvf6lrr71W/fv312effaZHH31UR48e1Z133mk5ThI2AADgCoasbcPR0j5b6tixY5o9e7YqKysVHx+v4cOHa/PmzbrpppskSeXl5YqK+mdCefz4cd11112qqqpS165dNWbMGO3cubPJRQrN8Zhm257J4Pf7FR8fr5qamhaNFQMAgPAL5+/vc+9etXeMOnWxt9Z0svas/mN0qePzEipsAADAFaweJdXSPt3AHVECAABEMCpsAADAFYJmlII2b+thd3+h4o4oAQAAIpilhC0YDOoXv/iF+vXrp06dOumKK67Qgw8+qDZetwAAACKQIU9ImhtYGhJ95JFHlJ+fr2effVZDhgzRnj17NGfOHMXHx+vuu+8OVYwAAAARzVLCtnPnTk2bNk1TpkyRJPXt21d/+MMftHv37pAEBwAAcA5z2FooPT1dW7Zs0bvvvitJ+utf/6odO3YoIyMjJMEBAACcc+6kA7ubG1iqsN17773y+/0aNGiQoqOjFQwGtWTJEs2aNavJZwKBQIMztvx+f+ujBQAAiECWErYXX3xRzz//vAoKCjRkyBCVlZVp4cKFSklJUVZWVqPP5OXl6YEHHrAlWAAAELkM0yPD7qOpbO4vVCwdTZWamqp7771X2dnZ9dceeughrVu3Tu+8806jzzRWYUtNTXX8ERAAAOCfnHA01a9KvhmSo6n+8+r/cXxeYulbf/755w0ONZWk6OhoGUbTR6d6vV55vd7WRQcAAPAlIwRzztxyNJWlhG3q1KlasmSJevfurSFDhmjfvn167LHHNHfu3FDFBwAAEPEsJWy//e1v9Ytf/EI/+MEPdOzYMaWkpOg//uM/dP/994cqPgAAAEmSYUbJsHkbDrv7CxVLCVtcXJyWL1+u5cuXhygcAAAAfB2HvwMAAFcIyqOgzUdJ2d1fqJCwAQAAV4jkIVF3RAkAABDBqLABAABXCMr+Icygrb2FDhU2AAAAh6PCBgAAXIE5bAAAAHAsKmwAAMAVgmaUgjZXxOzuL1TcESUAAEAEo8IGAABcwZRHhs2rRE2XbJxLhQ0AAMDhqLABAABXiOQ5bCRsAADAFQzTI8O0dwjT7v5CxR1pJQAAQASjwgYAAFwhqCgFba412d1fqLgjSgAAgAhGhQ0AALgCc9gAAADgWFTYAACAKxiKkmFzrcnu/kLFHVECAABEMCpsAADAFYKmR0Gb55zZ3V+okLABAABXYNEBAAAAHIsKGwAAcAXTjJJh89mfpkvOEnVHlAAAABGMChsAAHCFoDwKyuZFBzb3FypU2AAAAByOChsAAHAFw7R/Vadh2tpdyFBhAwAAcDgqbAAAwBWMEKwStbu/UCFhAwAArmDII8PmRQJ29xcq7kgrAQAAwiw/P1/Dhw+Xz+eTz+dTWlqaXn/99WafeemllzRo0CDFxsZq2LBheu2111r1bhI2AADgCufOErW7tVSvXr20dOlSlZaWas+ePbrhhhs0bdo0HTx4sNH7d+7cqZkzZ2revHnat2+fMjMzlZmZqQMHDlj+7h7TNNt0fYTf71d8fLxqamrk8/na8tUAAKCVwvn7+9y7/+3Nf1NMlxhb+z5de1oFNxS0+nt169ZNjz76qObNm3fez2bMmKG6ujpt3Lix/tq1116rkSNHauXKlZbeQ4UNAAC4wrlFB3a31ggGgyosLFRdXZ3S0tIavae4uFiTJk1qcG3y5MkqLi62/D4WHQAAgIjn9/sbfPZ6vfJ6vefdt3//fqWlpenUqVPq0qWL1q9fr8GDBzfaZ1VVlRITExtcS0xMVFVVleX4qLABAABXMOSRYdrcvlwlmpqaqvj4+PqWl5fXaAwDBw5UWVmZ3nrrLX3/+99XVlaW3n777ZB/dypsAAAg4lVUVDSYw9ZYdU2SYmJi1L9/f0nSmDFjVFJSoscff1yrVq06796kpCRVV1c3uFZdXa2kpCTL8VFhAwAArmB+uQ+bnc38ssJ2bquOc62phO3rDMNQIBBo9GdpaWnasmVLg2tFRUVNznlrDhU2AADgCueGMe3us6Vyc3OVkZGh3r1768SJEyooKNDWrVu1efNmSdLs2bPVs2fP+uHUBQsWaMKECVq2bJmmTJmiwsJC7dmzR6tXr7YcJwkbAABACxw7dkyzZ89WZWWl4uPjNXz4cG3evFk33XSTJKm8vFxRUf8cvExPT1dBQYF+/vOf67777tOAAQO0YcMGDR061PK7SdgAAKr4/CPt/keJTgZPKtGbqPTLrlXnDp3DHRbQQLjPEn366aeb/fnWrVvPuzZ9+nRNnz7daljnsZSw9e3bV0ePHj3v+g9+8AOtWLHiooMBALSt08ZprXr/Ke05XqooRcnj8cgwDRVWvKjZfW/XhB7fDHeIAGQxYSspKVEwGKz/fODAAd100022ZI4AgLb35AfPqPT4XkmSIUP68uybs+ZZPXNkreI6xGl015HhCxD4inDPYQsnS3XFHj16KCkpqb5t3LhRV1xxhSZMmBCq+AAAIVJ5skq7/1EiU42fUOiRR+s/3tC2QQFoVKvnsJ0+fVrr1q1TTk6OPJ6ms9NAINBguevXdxIGAITHuWFQQ0ajPzdlqvzzCn0a+FSXeS9r4+iA853bisPuPt2g1TP3NmzYoM8++0x33HFHs/fl5eU12Dk4NTW1ta8EANgoEAw0+wf3OaeCje8xBaDttDphe/rpp5WRkaGUlJRm78vNzVVNTU19q6ioaO0rAQA2Su6UpKAZbPaeDp4O6u7t1kYRAc2z/ViqEMyJC5VWDYkePXpUb7zxhl555ZUL3tvU4akAgPC6uttYPXe0QCeDJxv9eZSilN49TZ2iO7VxZEDjWHRg0Zo1a5SQkKApU6bYHQ8AoI3ERMXorsvnfrGdx9fm8UQpSt1iuml66q1hig7AV1musBmGoTVr1igrK0sdOrDvLgC42Ziuo/XTQT/Who//pP878Y6kLxK5b142Xpk9p8nXMS7MEQL/FMkVNssZ1xtvvKHy8nLNnTs3FPEAANrYIN9A3ev7iWrP1upU8JR8HeMVE9Ux3GEB+ArLCdvNN98s02x8zx4AgHt16dBFXTp0CXcYQJMiucJm74FcAAAAsB2T0AAAgCuYsn+jW7eMGVJhAwAAcDgqbAAAwBUieQ4bCRsAAHCFSE7YGBIFAABwOCpsAADAFaiwAQAAwLGosAEAAFegwgYAAADHosIGAABcwTQ9Mm2uiNndX6hQYQMAAHA4KmwAAMAVDHlsP5rK7v5ChYQNAAC4AosOAAAA4FhU2AAAgCuw6AAAAACORYUNAAC4AnPYAAAA4FhU2AAAgCswhw0AAACORYUNAAC4ghmCOWxuqbCRsAEAAFcwJZmm/X26AUOiAAAADkeFDQAAuIIhjzwRepYoFTYAAACHo8IGAABcgW09AAAA4FhU2AAAgCsYpkcejqYCAACAE1FhAwAArmCaIdiHzSUbsVFhAwAAcDgqbAAAwBUieZUoCRsAAHCFSE7YGBIFAABwOCpsAADAFdjWAwAAAM3Ky8vT1Vdfrbi4OCUkJCgzM1OHDh1q9pm1a9fK4/E0aLGxsZbfTcIGAABc4dy2Hna3ltq2bZuys7O1a9cuFRUV6cyZM7r55ptVV1fX7HM+n0+VlZX17ejRo5a/O0OiAAAALbBp06YGn9euXauEhASVlpbquuuua/I5j8ejpKSki3o3FTYAAOAKX1TEPDa31sdTU1MjSerWrVuz99XW1qpPnz5KTU3VtGnTdPDgQcvvImEDAAARz+/3N2iBQKDZ+w3D0MKFCzV+/HgNHTq0yfsGDhyoZ555Rq+++qrWrVsnwzCUnp6ujz76yFJ8lhO2jz/+WLfffru6d++uTp06adiwYdqzZ4/VbgAAACyxv7r2z33dUlNTFR8fX9/y8vKajSU7O1sHDhxQYWFhs/elpaVp9uzZGjlypCZMmKBXXnlFPXr00KpVqyx9d0tz2I4fP67x48fr+uuv1+uvv64ePXrovffeU9euXS29FAAAwCrzy2Z3n5JUUVEhn89Xf93r9Tb5zPz587Vx40Zt375dvXr1svS+jh07atSoUTp8+LCl5ywlbI888ohSU1O1Zs2a+mv9+vWz9EIAAACn8fl8DRK2xpimqR/+8Idav369tm7d2qocKBgMav/+/brlllssPWdpSPRPf/qTxo4dq+nTpyshIUGjRo3Sk08+aemFAAAArRHKIdGWyM7O1rp161RQUKC4uDhVVVWpqqpKJ0+erL9n9uzZys3Nrf/8y1/+Un/+85/1wQcfaO/evbr99tt19OhR3XnnnZa+u6WE7YMPPlB+fr4GDBigzZs36/vf/77uvvtuPfvss00+EwgEzpvIBwAA4Db5+fmqqanRxIkTlZycXN9eeOGF+nvKy8tVWVlZ//n48eO66667dNVVV+mWW26R3+/Xzp07NXjwYEvv9phmyxe0xsTEaOzYsdq5c2f9tbvvvlslJSUqLi5u9JnFixfrgQceOO96TU3NBUuPAADAGfx+v+Lj48Py+/vcuy9/9j5FX2L9lIDmBD8/pQ+yHnZ8XmKpwpacnHxeRnjVVVepvLy8yWdyc3NVU1NT3yoqKloXKQAAQISytOhg/Pjx552Z9e6776pPnz5NPuP1eptdaQEAANAiFuectbRPN7BUYbvnnnu0a9cuPfzwwzp8+LAKCgq0evVqZWdnhyo+AACAiGcpYbv66qu1fv16/eEPf9DQoUP14IMPavny5Zo1a1ao4gMAAJAU/sPfw8ny4e/f/va39e1vfzsUsQAAADTJ6jYcLe3TDThLFAAAwOEsV9gAAADCwvTYv0iAChsAAADsQIUNAAC4QigWCbhl0QEVNgAAAIejwgYAANzB/LLZ3acLUGEDAABwOCpsAADAFSJ5HzYSNgAA4B4uGcK0G0OiAAAADkeFDQAAuEIkD4lSYQMAAHA4KmwAAMAd2NYDAAAATkWFDQAAuITny2Z3n85HhQ0AAMDhqLABAAB3iOA5bCRsAADAHSI4YWNIFAAAwOGosAEAAHcwPV80u/t0ASpsAAAADkeFDQAAuIJpftHs7tMNqLABAAA4HBU2AADgDqwSBQAAgFNRYQMAAO4QwatESdgAAIAreMwvmt19ugFDogAAAA5HhQ0AALgDiw4AAADgVFTYAACAO0TwogMqbAAAAA5HhQ0AALgDc9gAAADgVFTYAACAO0RwhY2EDQAAuEMEJ2wMiQIAADgcFTYAAOAObOsBAAAAp6LCBgAAXIHD3wEAAOBYVNgAXLRPP/9cG955Wx+f8OvS2Fj9y8Cr1O/SruEOC0B7wyrRllm8eLE8Hk+DNmjQoFDFBsAFntxbovRnVmnp/27X8/v/qid279KNv39GP31js84Eg+EODwBsk5eXp6uvvlpxcXFKSEhQZmamDh06dMHnXnrpJQ0aNEixsbEaNmyYXnvtNcvvtjwkOmTIEFVWVta3HTt2WH4pgPbhpbcPKG/Hdp01DBmmqbOGoaD5xZ+rL799QEv+Z2tY4wMAO23btk3Z2dnatWuXioqKdObMGd18882qq6tr8pmdO3dq5syZmjdvnvbt26fMzExlZmbqwIEDlt5teUi0Q4cOSkpKsvoYgHYmaBhavmtnkz83JT2//6/KvuZa9bikc9sFBqDd8igEiw4s3Ltp06YGn9euXauEhASVlpbquuuua/SZxx9/XN/61rf0k5/8RJL04IMPqqioSE888YRWrlzZ4ndbrrC99957SklJ0eWXX65Zs2apvLy82fsDgYD8fn+DBsD93v70b6qsPdHsPUHT1JYP3m+jiACg9b6eqwQCgQs+U1NTI0nq1q1bk/cUFxdr0qRJDa5NnjxZxcXFluKzlLCNGzdOa9eu1aZNm5Sfn68jR47om9/8pk6caPr/tPPy8hQfH1/fUlNTLQUIwJk+P336gvdEeTyqO3OmDaIBEBHObZxrd5OUmpraIF/Jy8trNhTDMLRw4UKNHz9eQ4cObfK+qqoqJSYmNriWmJioqqoqS1/d0pBoRkZG/f8ePny4xo0bpz59+ujFF1/UvHnzGn0mNzdXOTk59Z/9fj9JG9AO9L20qzxqfoGVYZrq37XpvzwBwCkqKirk8/nqP3u93mbvz87O1oEDB9psLv9Fbetx6aWX6sorr9Thw4ebvMfr9V7wSwNwn8QuXXRDv8u19cMj9QsNvirK41FC5876Ru8+YYgOQLsUwm09fD5fg4StOfPnz9fGjRu1fft29erVq9l7k5KSVF1d3eBadXW15fUAF7Vxbm1trd5//30lJydfTDcAXGrRhBt0aWwnRXsaTtuN9ngU7fHosZtvUXQU+3MDaB9M09T8+fO1fv16vfnmm+rXr98Fn0lLS9OWLVsaXCsqKlJaWpqld1v6f9If//jH2rZtmz788EPt3LlT3/nOdxQdHa2ZM2daeimA9qGXL16vfneWvjNosDp+mZh5JE3o008v3/ZvurYX0x8A2MgMUWuh7OxsrVu3TgUFBYqLi1NVVZWqqqp08uTJ+ntmz56t3Nzc+s8LFizQpk2btGzZMr3zzjtavHix9uzZo/nz51v66paGRD/66CPNnDlTf//739WjRw994xvf0K5du9SjRw9LLwXQfqTE+fSrm76lBybeqL+f/Fw+b6x8TIMA0A7l5+dLkiZOnNjg+po1a3THHXdIksrLyxX1lZGF9PR0FRQU6Oc//7nuu+8+DRgwQBs2bGh2oUJjLCVshYWFljoHEDk6deyoXh3jwx0GgHYs3Ie/m43M1/26rVu3nndt+vTpmj59uoWozsdZogAAwB04SxQAAABORYUNAAC4AxU2AAAAOBUVNgAA4ArhXnQQTlTYAAAAHI4KGwAAcIevHNZua58uQIUNAADA4aiwAQAAd2CVKAAAAJyKChsAAHCFSF4lSsIGAADcgSFRAAAAOBUVNgAA4A4hGBKlwgYAAABbUGEDAADuwBw2AAAAOBUVNgAA4A5U2AAAAOBUVNgAAIArRPLGuVTYAAAAHI6EDQAAwOEYEgUAAO7AogMAAAA4FRU2AADgCiw6AAAAgGNRYQMAAO7hkoqY3aiwAQAAOBwVNgAA4A4RvEqUhA0AALgCiw4AAADgWFTYAACAO0TwkCgVNgAAAIejwgYAAFyBOWwAAABwLCpsAADAHZjDBgAAAKeiwgYAANwhgitsJGwAAMAVWHQAAAAAx6LCBgAA3CGCh0QvqsK2dOlSeTweLVy40KZwAAAA8HWtrrCVlJRo1apVGj58uJ3xAAAANI4KmzW1tbWaNWuWnnzySXXt2tXumAAAAPAVrUrYsrOzNWXKFE2aNMnueAAAABp1bpWo3c0NLA+JFhYWau/evSopKWnR/YFAQIFAoP6z3++3+koAAICIZqnCVlFRoQULFuj5559XbGxsi57Jy8tTfHx8fUtNTW1VoAAAIMKZIWouYClhKy0t1bFjxzR69Gh16NBBHTp00LZt2/Sb3/xGHTp0UDAYPO+Z3Nxc1dTU1LeKigrbggcAAJHDCUOi27dv19SpU5WSkiKPx6MNGzY0e//WrVvl8XjOa1VVVZbea2lI9MYbb9T+/fsbXJszZ44GDRqkn/70p4qOjj7vGa/XK6/XaykoAAAAJ6qrq9OIESM0d+5c3XrrrS1+7tChQ/L5fPWfExISLL3XUsIWFxenoUOHNrjWuXNnde/e/bzrAAAAtnLAth4ZGRnKyMiw/JqEhARdeumllp87h6OpAABAxPP7/Q3aVxdM2mHkyJFKTk7WTTfdpP/93/+1/PxFH021devWi+0CAADgwkJYYfv6oshFixZp8eLFF919cnKyVq5cqbFjxyoQCOipp57SxIkT9dZbb2n06NEt7oezRAEAQMSrqKhoMMfMrvn3AwcO1MCBA+s/p6en6/3339evf/1rPffccy3uh4QNAAC4gufLZnefkuTz+RokbKF0zTXXaMeOHZaeYQ4bAABAGyorK1NycrKlZ6iwAQAAd3DAKtHa2lodPny4/vORI0dUVlambt26qXfv3srNzdXHH3+s3//+95Kk5cuXq1+/fhoyZIhOnTqlp556Sm+++ab+/Oc/W3ovCRsAAHCFUJz9abW/PXv26Prrr6//nJOTI0nKysrS2rVrVVlZqfLy8vqfnz59Wj/60Y/08ccf65JLLtHw4cP1xhtvNOijZXGaZpseyuD3+xUfH6+ampo2GysGAAAXJ5y/v8+9e8j3Hla0t2VHY7ZUMHBKB1fe5/i8hAobAABwBwcMiYYLiw4AAAAcjgobAABwD5dUxOxGhQ0AAMDhqLABAABXcMIq0XChwgYAAOBwVNgAAIA7RPAqURI2AADgCgyJAgAAwLGosAEAAHeI4CFRKmwAAAAOR4UNAAC4AnPYAAAA4FhU2AAAgDswhw0AAABORYUNAAC4QwRX2EjYAACAK7DoAAAAAI5FhQ0AALhDBA+JUmEDAABwOCpsAADAFTymKY9pb0nM7v5ChQobAACAw1FhAwAA7sAcNgAAADgVFTYAAOAK7MMGAAAAx6LCBgAA3CGC57CRsAEAAFdgSBQAAACORYUNAAC4QwQPiVJhAwAAcDgqbAAAwBWYwwYAAADHosIGAADcgTlsAAAAcCoqbAi7wOmz2lr8rt55v0odO0Tr2lH9NGpoqjweT7hDAwA4jFvmnNnNUsKWn5+v/Px8ffjhh5KkIUOG6P7771dGRkYoYkME2HewQj/71avy155Sh+gomZIKXi3RgH4J+lXud9Sje1y4QwQAOIVpftHs7tMFLA2J9urVS0uXLlVpaan27NmjG264QdOmTdPBgwdDFR/asaMf/V0/euiPqq0LSJLOBg0Fg4Yk6YOjf9PCB17SmTPBcIYIAIAjWErYpk6dqltuuUUDBgzQlVdeqSVLlqhLly7atWtXqOJDO1b4X6UKng3KaOSvm6Bh6ujH/9D23e+FITIAgBOd29bD7uYGrV50EAwGVVhYqLq6OqWlpTV5XyAQkN/vb9AASXpz5zsKGk3/lxIV5dFfit9tw4gAAHAmywnb/v371aVLF3m9Xn3ve9/T+vXrNXjw4Cbvz8vLU3x8fH1LTU29qIDRfpwKnG3254Zh6vOTp9soGgCA45khai5gOWEbOHCgysrK9NZbb+n73/++srKy9Pbbbzd5f25urmpqaupbRUXFRQWM9iM1uauaWwgaHeVRv17d2y4gAAAcynLCFhMTo/79+2vMmDHKy8vTiBEj9Pjjjzd5v9frlc/na9AASbo1Y2Szf9kEDVP/ctPwNosHAOBsHiM0zQ0ueuNcwzAUCATsiAURZuqNwzV6WO/z9ls79/HO745XHypsAABY24ctNzdXGRkZ6t27t06cOKGCggJt3bpVmzdvDlV8aMc6dozWoz+7Vc+v360/vr5Pn/lPSpL6pV6mf791nG765lVhjhAA4CgRfDSVpYTt2LFjmj17tiorKxUfH6/hw4dr8+bNuummm0IVH9q5mI4dNOe2dP37v16rT/9Rq44dotXt0ks45QAAcJ5QbMPRLrf1ePrpp/Xhhx8qEAjo2LFjeuONN0jWYIsO0VFK6uFT966dSdYAAI61fft2TZ06VSkpKfJ4PNqwYcMFn9m6datGjx4tr9er/v37a+3atZbfy+HvAADAHc4dTWV3s6Curk4jRozQihUrWnT/kSNHNGXKFF1//fUqKyvTwoULdeedd1qeTsbh7wAAAC2UkZFh6Qz1lStXql+/flq2bJkk6aqrrtKOHTv061//WpMnT25xP1TYAACAK7jxaKri4mJNmjSpwbXJkyeruLjYUj9U2AAAQMT7+tGZXq9XXq/3ovutqqpSYmJig2uJiYny+/06efKkOnXq1KJ+qLABAAB3COHRVKmpqQ2O0szLy2uzr9USVNgAAEDEq6ioaHAakx3VNUlKSkpSdXV1g2vV1dXy+Xwtrq5JJGwAAMAlQrkPW6iOz0xLS9Nrr73W4FpRUZHS0tIs9cOQKAAAcAcHbOtRW1ursrIylZWVSfpi246ysjKVl5dL+uJUqNmzZ9ff/73vfU8ffPCB/vM//1PvvPOOfve73+nFF1/UPffcY+m9JGwAAAAttGfPHo0aNUqjRo2SJOXk5GjUqFG6//77JUmVlZX1yZsk9evXT//93/+toqIijRgxQsuWLdNTTz1laUsPiSFRAADgEk44mmrixIkym6nKNXaKwcSJE7Vv3z6LkTVEhQ0AAMDhqLABAAB3+Mo2HLb26QJU2AAAAByOChsAAHAFJ8xhCxcqbAAAAA5HhQ0AALiDYX7R7O7TBUjYAACAO7DoAAAAAE5FhQ0AALiCRyFYdGBvdyFDhQ0AAMDhqLABAAB3aMVh7S3q0wWosAEAADgcFTYAAOAKbJwLAAAAx6LCBgAA3CGC92EjYQMAAK7gMU15bF4kYHd/ocKQKAAAgMNRYQMAAO5gfNns7tMFqLABAAA4HBU2AADgCsxhAwAAgGNRYQMAAO4Qwdt6UGEDAABwOCpsAADAHSL48HcSNgAA4AqcJQoAAADHosIGAADcIYKHRKmwAQAAOBwVNgAA4Aoe44tmd59uQIUNAADA4aiwAQAAd2AOW8vk5eXp6quvVlxcnBISEpSZmalDhw6FKjYAAADIYsK2bds2ZWdna9euXSoqKtKZM2d08803q66uLlTxAQAAfMEMUXMBS0OimzZtavB57dq1SkhIUGlpqa677jpbAwMAAPgqj2nKY/MQpt39hcpFLTqoqamRJHXr1s2WYAAAAHC+Vi86MAxDCxcu1Pjx4zV06NAm7wsEAgoEAvWf/X5/a18JAAAiGYsOrMvOztaBAwdUWFjY7H15eXmKj4+vb6mpqa19JQAAQERqVcI2f/58bdy4UX/5y1/Uq1evZu/Nzc1VTU1NfauoqGhVoAAAIMKZkgybmzsKbNaGRE3T1A9/+EOtX79eW7duVb9+/S74jNfrldfrbXWAAAAAkc5Swpadna2CggK9+uqriouLU1VVlSQpPj5enTp1CkmAAAAAEqtEWyw/P181NTWaOHGikpOT69sLL7wQqvgAAAAinuUhUQAAgLAwFYJVovZ2Fyoc/g4AAOBwHP4OAADcIYL3YSNhAwAA7mBI8oSgTxdgSBQAAMDhqLABAABXYFsPAAAAtMiKFSvUt29fxcbGaty4cdq9e3eT965du1Yej6dBi42NtfxOEjYAAOAO5xYd2N0seOGFF5STk6NFixZp7969GjFihCZPnqxjx441+YzP51NlZWV9O3r0qOWvTsIGAADQQo899pjuuusuzZkzR4MHD9bKlSt1ySWX6JlnnmnyGY/Ho6SkpPqWmJho+b0kbAAAwB3CXGE7ffq0SktLNWnSpPprUVFRmjRpkoqLi5t8rra2Vn369FFqaqqmTZumgwcPWv7qJGwAACDi+f3+Bi0QCJx3z6effqpgMHhehSwxMbH+fPWvGzhwoJ555hm9+uqrWrdunQzDUHp6uj766CNL8ZGwAQAAdwhhhS01NVXx8fH1LS8vz5aQ09LSNHv2bI0cOVITJkzQK6+8oh49emjVqlWW+mFbDwAA4A4h3Di3oqJCPp+v/rLX6z3v1ssuu0zR0dGqrq5ucL26ulpJSUktel3Hjh01atQoHT582FKYVNgAAEDE8/l8DVpjCVtMTIzGjBmjLVu21F8zDENbtmxRWlpai94TDAa1f/9+JScnW4qPChsAAHAFJ2ycm5OTo6ysLI0dO1bXXHONli9frrq6Os2ZM0eSNHv2bPXs2bN+SPWXv/ylrr32WvXv31+fffaZHn30UR09elR33nmnpfeSsAEAALTQjBkz9Le//U3333+/qqqqNHLkSG3atKl+IUJ5ebmiov45gHn8+HHdddddqqqqUteuXTVmzBjt3LlTgwcPtvRej2m27ZkMfr9f8fHxqqmpaTBWDAAAnCucv7/PvXvSgHvUIfr8ocqLcTYY0Bvv/drxeQlz2AAAAByOIVEAAOAOhil5bB4YNDj8HQAAADagwgYAANyhFYe1t6hPFyBhAwAALhGChE3uSNgYEgUAAHA4KmwAAMAdInhIlAobAACAw1FhAwAA7mCYsn3OGdt6AAAAwA5U2AAAgDuYxhfN7j5dgAobAACAw1FhAwAA7hDBq0RJ2AAAgDuw6AAAAABORYUNAAC4QwQPiVJhAwAAcDgqbAAAwB1MhaDCZm93oUKFDQAAwOGosAEAAHdgDhsAAACcigobAABwB8OQZPNRUoY7jqYiYQMAAO7AkCgAAACcigobAABwhwiusLk+YTNNU/9v29va/dpenTl9VgPGXK4J09MUExsT7tAAAABsYTlh2759ux599FGVlpaqsrJS69evV2ZmZghCu7C/Vx7XL6bm6b29RxTdIVrySMEzQeXfs1b3v/Qjjbx+aFjiAgAAIcDh7y1XV1enESNGaMWKFaGIp8XOnjmrn970S33w/45KkoJngwqeCUqSaj+r031THtbRtyvCGSIAAIAtLFfYMjIylJGREYpYLNn5aomOvv1Roz8zDVPG2aBefmyjfvTU99s4MgAAEAqmacg07d2Gw+7+QiXkq0QDgYD8fn+DZof/eeUtRUU3HX7wrKFtL+605V0AAADhFPKELS8vT/Hx8fUtNTXVln4/95+UEWw+Kz71eUCmS1Z/AACACzDNL+ac2dlckieEPGHLzc1VTU1NfauosGdeWZ+reiq6Q9Phezwe9RyQLI/HY8v7AABAmJ3b1sPu5gIhT9i8Xq98Pl+DZodb7pqk4NnmK2zTfvAtW94FAAAQTq496aDXlSma89BMSZInqmEVzRPl0fAJg3XL/zcpHKEBAIBQMIzQNBewvEq0trZWhw8frv985MgRlZWVqVu3burdu7etwV3Iv913q5IvT9Qf8l7Rkf3lkqT4y+L0Lz/4lr57b6ZivB3bNB4AAIBQsJyw7dmzR9dff33955ycHElSVlaW1q5da1tgLXX9d8dr4ox0Ha/+TGdPn1X3lG5fbKILAADaFzMEG+e6ZA6b5YRt4sSJjlt56fF41C2pa7jDAAAACAnXnyUKAAAig2kYMj1snAsAAAAHosIGAADcgTlsAAAADmeYkicyEzaGRAEAAByOChsAAHAH05Rk8yIBKmwAAACwAxU2AADgCqZhyrR5DpvT9pZtChU2AAAAh6PCBgAA3ME0ZP8cNjbOBQAAaHdWrFihvn37KjY2VuPGjdPu3bubvf+ll17SoEGDFBsbq2HDhum1116z/E4SNgAA4AqmYYakWfHCCy8oJydHixYt0t69ezVixAhNnjxZx44da/T+nTt3aubMmZo3b5727dunzMxMZWZm6sCBA5be6zHbeLad3+9XfHy8ampq5PP52vLVAACglcL5+/vcuydqmjp4Otra91nzjLbq1RZ/r3Hjxunqq6/WE088IUkyDEOpqan64Q9/qHvvvfe8+2fMmKG6ujpt3Lix/tq1116rkSNHauXKlS2Os83nsJ3LD/1+f1u/GgAAtNK539vhXFV5VmdsP5nqrM5IOj8v8Xq98nq9Da6dPn1apaWlys3Nrb8WFRWlSZMmqbi4uNH+i4uLlZOT0+Da5MmTtWHDBktxtnnCduLECUlSampqW78aAABcpBMnTig+Pr5N3xkTE6OkpCTtqLI+96slunTpcl5esmjRIi1evLjBtU8//VTBYFCJiYkNricmJuqdd95ptO+qqqpG76+qqrIUY5snbCkpKaqoqFBcXJw8Ho9t/fr9fqWmpqqioqLdDrW29+/I93O/9v4d+X7u196/Yyi/n2maOnHihFJSUmzttyViY2N15MgRnT59OiT9m6Z5Xk7y9epauLV5whYVFaVevXqFrH+fz9cu/yP8qvb+Hfl+7tfevyPfz/3a+3cM1fdr68raV8XGxio2NjZs75ekyy67TNHR0aqurm5wvbq6WklJSY0+k5SUZOn+prBKFAAAoAViYmI0ZswYbdmypf6aYRjasmWL0tLSGn0mLS2twf2SVFRU1OT9TWHjXAAAgBbKyclRVlaWxo4dq2uuuUbLly9XXV2d5syZI0maPXu2evbsqby8PEnSggULNGHCBC1btkxTpkxRYWGh9uzZo9WrV1t6b7tJ2LxerxYtWuS4MWc7tffvyPdzv/b+Hfl+7tfev2N7/35OMGPGDP3tb3/T/fffr6qqKo0cOVKbNm2qX1hQXl6uqKh/DmCmp6eroKBAP//5z3XfffdpwIAB2rBhg4YOHWrpvW2+DxsAAACsYQ4bAACAw5GwAQAAOBwJGwAAgMORsAEAADhcu0nYVqxYob59+yo2Nlbjxo3T7t27wx2SbbZv366pU6cqJSVFHo/H8vljTpaXl6err75acXFxSkhIUGZmpg4dOhTusGyVn5+v4cOH129kmZaWptdffz3cYYXM0qVL5fF4tHDhwnCHYpvFixfL4/E0aIMGDQp3WLb6+OOPdfvtt6t79+7q1KmThg0bpj179oQ7LFv07dv3vH8/j8ej7OzscIdmm2AwqF/84hfq16+fOnXqpCuuuEIPPvhgWM/9hL3aRcL2wgsvKCcnR4sWLdLevXs1YsQITZ48WceOHQt3aLaoq6vTiBEjtGLFinCHYrtt27YpOztbu3btUlFRkc6cOaObb75ZdXV14Q7NNr169dLSpUtVWlqqPXv26IYbbtC0adN08ODBcIdmu5KSEq1atUrDhw8Pdyi2GzJkiCorK+vbjh07wh2SbY4fP67x48erY8eOev311/X2229r2bJl6tq1a7hDs0VJSUmDf7uioiJJ0vTp08McmX0eeeQR5efn64knntD//d//6ZFHHtGvfvUr/fa3vw13aLCL2Q5cc801ZnZ2dv3nYDBopqSkmHl5eWGMKjQkmevXrw93GCFz7NgxU5K5bdu2cIcSUl27djWfeuqpcIdhqxMnTpgDBgwwi4qKzAkTJpgLFiwId0i2WbRokTlixIhwhxEyP/3pT81vfOMb4Q6jzSxYsMC84oorTMMwwh2KbaZMmWLOnTu3wbVbb73VnDVrVpgigt1cX2E7ffq0SktLNWnSpPprUVFRmjRpkoqLi8MYGVqjpqZGktStW7cwRxIawWBQhYWFqqurs3wsidNlZ2drypQpDf5bbE/ee+89paSk6PLLL9esWbNUXl4e7pBs86c//Uljx47V9OnTlZCQoFGjRunJJ58Md1ghcfr0aa1bt05z584977BvN0tPT9eWLVv07rvvSpL++te/aseOHcrIyAhzZLCL6086+PTTTxUMBut3GD4nMTFR77zzTpiiQmsYhqGFCxdq/PjxlneAdrr9+/crLS1Np06dUpcuXbR+/XoNHjw43GHZprCwUHv37lVJSUm4QwmJcePGae3atRo4cKAqKyv1wAMP6Jvf/KYOHDiguLi4cId30T744APl5+crJydH9913n0pKSnT33XcrJiZGWVlZ4Q7PVhs2bNBnn32mO+64I9yh2Oree++V3+/XoEGDFB0drWAwqCVLlmjWrFnhDg02cX3ChvYjOztbBw4caFdzg84ZOHCgysrKVFNTo5dffllZWVnatm1bu0jaKioqtGDBAhUVFSk2Njbc4YTEV6sUw4cP17hx49SnTx+9+OKLmjdvXhgjs4dhGBo7dqwefvhhSdKoUaN04MABrVy5st0lbE8//bQyMjKUkpIS7lBs9eKLL+r5559XQUGBhgwZorKyMi1cuFApKSnt7t8wUrk+YbvssssUHR2t6urqBterq6uVlJQUpqhg1fz587Vx40Zt375dvXr1Cnc4touJiVH//v0lSWPGjFFJSYkef/xxrVq1KsyRXbzS0lIdO3ZMo0ePrr8WDAa1fft2PfHEEwoEAoqOjg5jhPa79NJLdeWVV+rw4cPhDsUWycnJ5/3xcNVVV+mPf/xjmCIKjaNHj+qNN97QK6+8Eu5QbPeTn/xE9957r7773e9KkoYNG6ajR48qLy+PhK2dcP0ctpiYGI0ZM0Zbtmypv2YYhrZs2dLu5gi1R6Zpav78+Vq/fr3efPNN9evXL9whtQnDMBQIBMIdhi1uvPFG7d+/X2VlZfVt7NixmjVrlsrKytpdsiZJtbW1ev/995WcnBzuUGwxfvz487bTeffdd9WnT58wRRQaa9asUUJCgqZMmRLuUGz3+eefNzhwXJKio6NlGEaYIoLdXF9hk6ScnBxlZWVp7Nixuuaaa7R8+XLV1dVpzpw54Q7NFrW1tQ3+kj9y5IjKysrUrVs39e7dO4yRXbzs7GwVFBTo1VdfVVxcnKqqqiRJ8fHx6tSpU5ijs0dubq4yMjLUu3dvnThxQgUFBdq6das2b94c7tBsERcXd96cw86dO6t79+7tZi7ij3/8Y02dOlV9+vTRJ598okWLFik6OlozZ84Md2i2uOeee5Senq6HH35Yt912m3bv3q3Vq1dr9erV4Q7NNoZhaM2aNcrKylKHDu3iV18DU6dO1ZIlS9S7d28NGTJE+/bt02OPPaa5c+eGOzTYJdzLVO3y29/+1uzdu7cZExNjXnPNNeauXbvCHZJt/vKXv5iSzmtZWVnhDu2iNfa9JJlr1qwJd2i2mTt3rtmnTx8zJibG7NGjh3njjTeaf/7zn8MdVki1t209ZsyYYSYnJ5sxMTFmz549zRkzZpiHDx8Od1i2+q//+i9z6NChptfrNQcNGmSuXr063CHZavPmzaYk89ChQ+EOJST8fr+5YMECs3fv3mZsbKx5+eWXmz/72c/MQCAQ7tBgE49psg0yAACAk7l+DhsAAEB7R8IGAADgcCRsAAAADkfCBgAA4HAkbAAAAA5HwgYAAOBwJGwAAAAOR8IGAADgcCRsAAAADkfCBgAA4HAkbAAAAA5HwgYAAOBw/z/W9BYt44AfdQAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 800x600 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.figure(figsize=(8,6))\n",
    "scatter = plt.scatter(X[:,0],X[:,1],c=y)\n",
    "plt.colorbar(scatter)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "9307ca1b-04f6-482e-8052-268d1c4fe24a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[2, 1]"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54f45a0d-5621-4188-ac42-80247d055903",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
